apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-cicd-service
  namespace: multi-cloud-cicd
  labels:
    app.kubernetes.io/name: multi-cloud-cicd
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: multi-cloud-cicd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: multi-cloud-cicd
    app.kubernetes.io/component: web
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
